export default {
mainarea :[{title:'Administrativo'},
{title:'Construção'},
{title:'Cuidado de Animais'},
{title:'Industrial'},
{title:'Limpeza'},
{title:'Restaurante'},
{title:'Saúde'},
{title:'Serviços Gerais'},
{title:'Telemarketing'},
{title:'Transporte'},
{title:'Varejo'},
{title:'Vendas'},
            ],
items1 :[  {label: 'Assistente Administrativo', value: 'Assistente Administrativo'},
            {label: 'Escrituário', value: 'Escrituário'},
            {label: 'Office Boy', value: 'Office Boy'},
            {label: 'Recepcionista', value: 'Recepcionista'},
            {label: 'Secretária', value: 'Secretária'},
        ],
items2 : [
            {label: 'Carpiteiro', value: 'Carpiteiro'},
            {label: 'Eletricista', value: 'Eletricista'},
            {label: 'Encanador', value: 'Encanador'},
            {label: 'Pedreiro', value: 'Pedreiro'},
            {label: 'Pintor', value: 'Pintor'},
        ],
items3 : [
            {label: 'Banhista', value: 'Banhista'},
            {label: 'Tosador', value: 'Tosador'},
        ],
items4 : [
            {label: 'Auxiliar de Produção', value: 'Auxiliar de Produção'},
            {label: 'Caldeireiro', value: 'Caldeireiro'},
            {label: 'Ferramenteiro', value: 'Ferramenteiro'},
            {label: 'Fresador', value: 'Fresador'},
            {label: 'Funileiro', value: 'Funileiro'},
            {label: 'Mecanico Industrial', value: 'Mecanico Industrial'},
            {label: 'Operador de Máquinas', value: 'Operador de Máquinas'},
            {label: 'Serralheiro', value: 'Serralheiro'},
            {label: 'Soldador', value: 'Soldador'},
            {label: 'Torneiro', value: 'Torneiro'},
        ],
items5 : [
            {label: 'Auxiliar de Limpeza', value: 'Auxiliar de Limpeza'},
            {label: 'Doméstica', value: 'Doméstica'},
            {label: 'Faxineiro', value: 'Faxineiro'},
            {label: 'Lavador de Auto', value: 'Lavador de Auto'},
            {label: 'Limpador de Vidros', value: 'Limpador de Vidros'},
            {label: 'Operador de Varredeira', value: 'Operador de Varredeira'},
            {label: 'Supervisor de Limpeza', value: 'Supervisor de Limpeza'},
        ],
items6 : [
            {label: 'Ajudante de Cozinha', value: 'Ajudante de Cozinha'},
            {label: 'Atendente', value: 'Atendente'},
            {label: 'Auxiliar de Garçom', value: 'Auxiliar de Garçom'},
            {label: 'Barista', value: 'Barista'},
            {label: 'Barman', value: 'Barman'},
            {label: 'Cozinheiro', value: 'Cozinheiro'},
            {label: 'Garçom', value: 'Garçom'},
            {label: 'Masseiro', value: 'Masseiro'},
            {label: 'Pizzaiolo', value: 'Pizzaiolo'},
            {label: 'Sushiman', value: 'Sushiman'},
        ],
items7 : [
            {label: 'Assistente Administrativo', value: 'Assistente Administrativo'},
            {label: 'Atendente de Farmácia', value: 'Atendente de Farmácia'},
            {label: 'Auxiliar Hospitalar', value: 'Auxiliar Hospitalar'},
            {label: 'Auxiliar de Enfermagem', value: 'Auxiliar de Enfermagem'},
            {label: 'Auxiliar de Limpeza Hospitalar', value: 'Auxiliar de Limpeza Hospitalar'},
            {label: 'Estoquista Hospitalar', value: 'Estoquista Hospitalar'},
            {label: 'Farmaceutico', value: 'Farmaceutico'},
            {label: 'Recepcionista Hospitalar', value: 'Recepcionista Hospitalar'},
            {label: 'Técnico de Análises Clínicas', value: 'Técnico de Análises Clínicas'},
            {label: 'Técnico de Coleta', value: 'Técnico de Coleta'},
            {label: 'Técnico de Enfermagem', value: 'Técnico de Enfermagem'},
            {label: 'Técnico de Patologia Clínica', value: 'Técnico de Patologia Clínica'},
],
items8 : [
            {label: 'Aux. Tec. Em Telecom', value: 'Aux. Tec. Em Telecom'},
            {label: 'Auxiliar de Manutenção', value: 'Auxiliar de Manutenção'},
            {label: 'Auxiliar de Serviços Gerais', value: 'Auxiliar de Serviços Gerais'},
            {label: 'Bombeiro', value: 'Bombeiro'},
            {label: 'Copeira', value: 'Copeira'},
            {label: 'Frentista', value: 'Frentista'},
            {label: 'Jardineiro', value: 'Jardineiro'},
            {label: 'Limpador de Piscina', value: 'Limpador de Piscina'},
            {label: 'Porteiro', value: 'Porteiro'},
            {label: 'Segurança', value: 'Segurança'},
            {label: 'Vigilante', value: 'Vigilante'},
            {label: 'Zelador', value: 'Zelador'},
            
],
items9 : [
            {label: 'Analista de Help Desk', value: 'Analista de Help Desk'},
            {label: 'Operador de Call Center', value: 'Operador de Call Center'},
            {label: 'Operador de Call Center Ativo', value: 'Operador de Call Center Ativo'},
            {label: 'Operador de Call Center Receptivo', value: 'Operador de Call Center Receptivo'},
            {label: 'Operador de Cobrança', value: 'Operador de Cobrança'},
        ],
items10 : [
            {label: 'Ajudante de Entrega', value: 'Ajudante de Entrega'},
            {label: 'Auxiliar de Logística', value: 'Auxiliar de Logística'},
            {label: 'Auxiliar de Motorista', value: 'Auxiliar de Motorista'},
            {label: 'Manobrista', value: 'Manobrista'},
            {label: 'Motoboy', value: 'Motoboy'},
            {label: 'Motorista Entregador', value: 'Motorista Entregador'},
            {label: 'Operador de Estacionamento', value: 'Operador de Estacionamento'},
            {label: 'Tratorista', value: 'Tratorista'},
        ],
items11 : [
            {label: 'Ajudante de Padeiro', value: 'Ajudante de Padeiro'},
            {label: 'Atendente de Loja', value: 'Atendente de Loja'},
            {label: 'Açougueiro', value: 'Açougueiro'},
            {label: 'Balconista', value: 'Balconista'},
            {label: 'Cartazista', value: 'Cartazista'},
            {label: 'Confeiteiro', value: 'Confeiteiro'},
            {label: 'Conferente', value: 'Conferente'},
            {label: 'Especialista em Frios', value: 'Especialista em Frios'},
            {label: 'Especialista em Queijos', value: 'Especialista em Queijos'},
            {label: 'Estoquista', value: 'Estoquista'},
            {label: 'Feirante', value: 'Feirante'},
            {label: 'Fiscal de Loja', value: 'Fiscal de Loja'},
            {label: 'Operador de Caixa', value: 'Operador de Caixa'},
            {label: 'Padeiro', value: 'Padeiro'},
            {label: 'Peixeiro', value: 'Peixeiro'},
            {label: 'Repositor', value: 'Repositor'},
            {label: 'Shopper', value: 'Shopper'},
            {label: 'Visual Merchandising', value: 'Visual Merchandising'},
            ],
items12 : [
            {label: 'Assistente Comercial', value: 'Assistente Comercial'},
            {label: 'Atendente de Loja', value: 'Atendente de Loja'},
            {label: 'Balconista', value: 'Balconista'},
            {label: 'Corretor de Imóveis', value: 'Corretor de Imóveis'},
            {label: 'Promotor de Vendas', value: 'Promotor de Vendas'},
            {label: 'Vendedor', value: 'Vendedor'},
            {label: 'Vendedor Externo', value: 'Vendedor Externo'},
        ],
}
